### ISSUE TITLE
Hi, I love this project!

### ISSUE THREAD

**Issue by zoecarver** [Rocla/lfs-7.8#6] opened 2016-08-28 21:29 UTC
I have one question, I am trying to run 6.all-2  and am getting this error:

`bash: ./6.40-chroot_expat.sh: /bin/bash: bad interpreter: No such file or directory`

thanks again for making this cool tool!

More info:
`lfs-7.8 git:(master) ✗ sudo ./6.4-root_chroot-environment.sh
### ---------------------------

... Loading commun functions and variables

... Validating the environment

/dev/sdb2: UUID="51a7b18c-fcc5-40ef-b5dd-e093a6f8fd8a" TYPE="ext4" PARTUUID="38a452b5-02"
!! Info: /dev/sdb2 is correctly mounted

/dev/sdb1                               partition   2097148 0   -1
!! Info: /dev/sdb1 is correctly configured as swap

... Entering the Chroot Environment
###### ### END OF CHAPTER 6.4

///// HUMAN REQUIRED \\\\\
--> Note that the bash prompt will say "I have no name!" This is normal because the /etc/passwd file has not been created yet.
### ./6.all-part-2-chroot_installing-basic-system.sh

I have no name!:/# cd tools/lfs
<./6.all-part-2-chroot_installing-basic-system.sh 
bash: ./6.all-part-2-chroot_installing-basic-system.sh: /bin/bash: bad interpreter: No such file or directory
I have no name!:/tools/lfs# ./6.40-chroot_expat.sh  
bash: ./6.40-chroot_expat.sh: /bin/bash: bad interpreter: No such file or directory
I have no name!:/tools/lfs# 
`

**Comment by RomainClaret** [comment] 2016-08-28 22:10
👋 just passing by to say I am active, thank you for submitting your issue, I will look into it tomorrow 😊 it's 00:10 here

**Comment by zoecarver** [comment] 2016-08-29 04:17
thanks so much!, I was hoping it was still active.

**Comment by RomainClaret** [comment] 2016-08-29 08:02
hi I am back.
Hmm. Do you have more log maybe? 
Did you go manual at some point? Or did you have errors during the process before?
What machine are you using, Real, Virtual?
It's strange because the bash interpreter is the same for the 6.39 😛 It should be just compilation :s

**Comment by zoecarver** [comment] 2016-08-29 14:00
Yeah, I was confused too, because bash is there, I was thinking that it might be because bash is in /tools/bin/bash, not /bin/bash? I am running ubuntu, however I installed all the dependency's(I think).

thanks again!

**Comment by zoecarver** [comment] 2016-08-29 14:02
this is where bash is located:

```
I have no name!:/tools/bin# ls bash
bash
I have no name!:/tools/bin# pwd
/tools/bin
I have no name!:/tools/bin# 

```

**Comment by zoecarver** [comment] 2016-08-29 14:03
oh and I forgot to say that I am not running a VM, sorry for all of the posts.

Thanks

**Comment by RomainClaret** [comment] 2016-08-29 18:41
hmm... I didn't try on ubuntu to be honest (i tested on debian), I will run the script a ubuntu VM on my side too. Could you give me your setup info? Ubuntu version maybe? Or maybe a snapshot, now I don't know about the privacy of your setup. 
Yeah.. I am really confused about your situation right now.

**Comment by RomainClaret** [comment] 2016-08-29 18:43
Did you try to run the script manually again?

**Comment by RomainClaret** [comment] 2016-08-29 18:44
Oh! I think about something, maybe the syntax of file... something is wrong with it

**Comment by RomainClaret** [comment] 2016-08-29 18:52
Do you see on the following lines there are excessive tabulations

https://github.com/Rocla/lfs-7.8/blob/master/6.40-chroot_expat.sh#L59
https://github.com/Rocla/lfs-7.8/blob/master/6.40-chroot_expat.sh#L65
https://github.com/Rocla/lfs-7.8/blob/master/6.40-chroot_expat.sh#L70

**Comment by zoecarver** [comment] 2016-08-29 18:55
thanks, however I have no idea what that means. how should I fix it? thanks again!

**Comment by RomainClaret** [comment] 2016-08-29 19:19
okay, no problem. I push a fix

**Comment by RomainClaret** [comment] 2016-08-29 19:21
Could you pull and try again? I am not sure it will work tho! I just notice that the carriage return character was present in the code, and it shouldn't have.

**Comment by zoecarver** [comment] 2016-08-29 19:21
thanks, I am making a snapshot that I can send you if you still need it.

**Comment by RomainClaret** [comment] 2016-08-29 19:22
The snapshot would be lovely! Thank you!

**Comment by zoecarver** [comment] 2016-08-29 19:47
it might take a while (4gb) Ill share a link with you

**Comment by RomainClaret** [comment] 2016-08-29 19:53
okay, thank you so much!

**Comment by zoecarver** [comment] 2016-08-30 19:30
Sorry about the wait... my internet is dreadfully slow. here is a link to a snapshot of the "final" copy: https://drive.google.com/open?id=0B1KZa-7dVNsnTC1RNDU4ejFkT3c 
however I cannot seem to get it to work... When I boot there is just a blinking line. I was wondering if you had some extra time could you look this over for me? if not I totally understand.

thanks again for this awesome project!

**Comment by RomainClaret** [comment] 2016-08-30 20:01
Okay :) I will download and take a look at what you have

**Comment by RomainClaret** [comment] 2016-08-30 20:02
Are you in 32 or 64 bits?

**Comment by zoecarver** [comment] 2016-08-30 20:22
64

**Comment by RomainClaret** [comment] 2016-08-30 20:27
Okay, so... I didn't try the scripts on a 64 bit maybe the problem comes from here. I know where to look at now :)

**Comment by RomainClaret** [comment] 2016-08-30 21:15
ZoeLe, question, I have the instructions in french, https://github.com/Rocla/lfs-7.8/blob/master/miscellaneous/Instructions_FR.pdf maybe you will understand some steps? Did you do similar steps?

**Comment by RomainClaret** [comment] 2016-08-30 21:23
so you know, i finished downloading your snapshot. I didn't look at it yet. I am currently trying the script on a vm with a fresh ubuntu 16.04.1 x64.

**Comment by zoecarver** [comment] 2016-08-30 22:24
I read the PDF, also I have been fallowing along with the LFS book (online)

**Comment by zoecarver** [comment] 2016-08-30 22:34
Thanks again for all your help!

**Comment by RomainClaret** [comment] 2016-08-30 22:46
np :) just noticed I did a mistake with my VM (not the script) I will have to restart the process tomorrow :( sorry for the long delay. I looked at the file you linked. If I understand it right, it's a bootable file, right? I put it on a USB key, and I run it from the bios? I am just wondering if what you are calling a "blinking line" is actually the LFS partition? If it's the case it's normal for the "blinking line" it's because there is nothing to boot on :-p the work should be done from the "host" machine connected to the "lfs" machine. I will be looking into more details what I can do with the file you provided.

**Comment by RomainClaret** [comment] 2016-08-30 22:48
read "machine" as "hdd"

**Comment by zoecarver** [comment] 2016-08-30 23:39
The file is bootable, from the book it sounded like you can boot onto the LFS hhd. When I (tried to) do this I got a blinking line. Thanks again.

**Comment by RomainClaret** [comment] 2016-08-31 13:16
Hmm, so I cannot boot from your file :-/ medium not found. I cannot reproduce the "blinking line".
On another end, to be able to "boot" we need to configure the bootscript in chapter 7 and set the grub in chapter 8.

Now to come back to your error, I could reproduce it! But only when I played with the snapshots when I went to old states of the system but with different scripts.

I will reinstall Ubuntu from scratch and run the script again with the modification, and see if something happens :)

**Comment by zoecarver** [comment] 2016-08-31 15:34
I know that this is totally unrelated, but ubuntu just crashed on me for the third time in a row, after I type `sudo -i` I tried it on two other machines and the same thing happened...

**Comment by zoecarver** [comment] 2016-08-31 15:39
never mind... I fixed it by logging in as root.

**Comment by zoecarver** [comment] 2016-08-31 15:49
I retried chapter 7 and 8... still nothing when I boot into the disk, however the boot directory is there:

boot ls
config-4.4.2  grub  System.map-4.4.2  vmlinuz-4.4.2-lfs-7.9

**Comment by RomainClaret** [comment] 2016-08-31 16:10
I don't know why it's closing the issue when I submit a related commit to this issue.. I will look into it later...

I found the problem with My "bad interpreter" error and I fixed it. The script is running at this time (chapter 6), I will see if new errors pops up. I don't know yet if what I am doing is directly fixing your problem, but I am debugging :)

**Comment by RomainClaret** [comment] 2016-08-31 16:18
hmm... I will look into your file a bit later when I am sure that on my side the scripts are doing what they are supposed to do :p

Thank you for your patience! When I made the script I didn't try and debug it on x64 or Ubuntu

**Comment by zoecarver** [comment] 2016-08-31 16:26
NP, thanks for all your time and help!

**Comment by RomainClaret** [comment] 2016-08-31 19:38
hahaha, omg, x64 is such a pain in the butt...

**Comment by zoecarver** [comment] 2016-08-31 22:55
Why?

**Comment by RomainClaret** [comment] 2016-09-01 10:18
Well, in our case, because I feel like LFS 7.8 wasn't designed for x64, to begin with, then community patched this up. But it's only my opinion.

Quoting page 8 and 9:

> the 64-bit build is only 4% faster and is 9% larger than the 32-bit build. The gain from going to a 64-bit system is relatively minimal. Of course, if you have more than 4GB of RAM or want to manipulate data that exceeds 4GB, the advantages of a 64-bit system are substantial.
> 
> The default 64-bit build that results from LFS is considered a "pure" 64-bit system. That is, it supports 64-bit executables only. Building a "multi-lib" system requires compiling many applications twice, once for a 32-bit system and once for a 64-bit system. This is not directly supported in LFS because it would interfere with the educational objective of providing the instructions needed for a straightforward base Linux system.
> 
> There are some older packages that cannot currently be built in a "pure" 64-bit system or require specialized build instructions. Generally, these packages have some embedded 32-bit specific assembly language instructions that fail when building on a 64-bit system.

I am currently going script by script and reading all the logs to find out where it goes wrong... Because 6.17-chroot_gcc.sh fails and it screws everything coming after.

But, I think I fixed your problem :p But I detected another problem with my VM configuration, and I am trying to fix it too.

**Comment by zoecarver** [comment] 2016-09-01 15:00
OK, thanks. Does that mean I should build my system on a 32 bit VM? If so is there any way to make it a 64 bit LFS system later? Thanks!

**Comment by zoecarver** [comment] 2016-09-01 15:02
Also have you thought about LFS 7.9/7.10? How hard would it be to upgrade?

**Comment by zoecarver** [comment] 2016-09-01 15:03
And you did fix my problem, thanks!

**Comment by RomainClaret** [comment] 2016-09-01 15:15
Well, to be honest, it's not something that I can't answer, it depends on you. When I made this script, I was targeting Debian 7.8.0 32bit. I integrated the 64bit recommendations just in case I would one day move to 64bit, and indeed I did with this issue :) Building a LFS, even with the book, you have to be prepared to have problems and solve them, that's the way it goes.

Plus, LFS is more, in my opinion, an academic need, just to know how it's done, but it's not to use as an everyday OS, but I am sure people will argue with me on this.

Back to your question. It depends on you, what are your needs? Why are you making a LFS? Will you use it later? What will you do with it? etc.. BUT you should know that you cannot go from pure 32bit to pure 64bit or pure 64bit to pure 32bit once it's done, you will have to rebuild LFS. However, a 32bit software could work in a 64bit environment if you also install the 32bit libraries (multi-lib).

**Comment by RomainClaret** [comment] 2016-09-01 15:20
I didn't look at LFS 7.9 or 7.10 in details yet. But no, it's should be hard to upgrade ;)

**Comment by RomainClaret** [comment] 2016-09-01 15:23
Just to be clear, I am talking about upgrading the scripts. Create lfs-7.9 and lfs-7.10 scripts. We would have to rebuild LFS. We won't be able to go from a built lfs-7.8 to lfs-7.9 or lfs-7.10 with an OS patch.

**Comment by zoecarver** [comment] 2016-09-01 16:34
Thanks again for all your help, I was planning on making an LFS system that I could use as a primary os. And add some extra stuff too like package managers, desktop environment, etc. However after saying that, I also did it to learn about linux, my plan was to use the scripts for the long somewhat tedious parts such as chapter 5 and 6. I would defenently prefer a 64bit system, however the one I made (with your scripts) does not seem to boot. I was wondering if you have any ideas about why that is? I re-ran 7.all and 8.all on the disk image I sent you. What should be my next step? Thanks!

**Comment by RomainClaret** [comment] 2016-09-01 17:01
Okay, well, why not :) However be prepared to solve a lot of problems, that's all I have to say :p 
I hope you are also aware that LFS provides only the basic GNU tools. You will have some work to get a user-friendly OS. Read: http://www.linuxfromscratch.org/blfs/.

On my side, I just finished compiling and installing GCC on my LFS made with Ubuntu x64 14.04.1; I think it worked this time. I am now crossing the fingers for the rest. Note that I just fully sequential on this one, script by script, I am not using "all" files.

Well, I think you should restart the process from scratch... Wipe the lfs partition, and restart the process.

Could you tell me your host configuration? What version of ubuntu are you using? What are the CPU, RAM, and HD space?

**Comment by zoecarver** [comment] 2016-09-01 19:02
sorry about my delayed response... my specs are :
-8gb ram
-Intel® Core™ i7-4770S CPU @ 3.10GHz × 8 
-Gallium 0.4 on NVE7
-Ubuntu 16.04 LTS 64-bit
-109.7 GB SSD

**Comment by zoecarver** [comment] 2016-09-01 19:03
I was original using a USB thumb drive as my LFS system drive. also if it was not clear theses are my host system specs.

thanks

**Comment by RomainClaret** [comment] 2016-09-01 20:57
Yeah! It worked! 
<img width="728" alt="screen shot 2016-09-01 at 22 56 36" src="https://cloud.githubusercontent.com/assets/8895475/18184057/72d9111c-7097-11e6-970a-7fc4df2d772b.png">

**Comment by RomainClaret** [comment] 2016-09-01 21:00
Okay, so you know, I used **Sequential** process from the read me https://github.com/Rocla/lfs-7.8#how-to-start script one by one, and reading all the steps.

**Comment by RomainClaret** [comment] 2016-09-01 21:04
I never tried yet with an USB key, what I know is that you should not run 8.all, because it's using the grub from the host, to create a "dual boot".
You must at step 8.4 take the correct actions explain in the book.

**Comment by RomainClaret** [comment] 2016-09-01 21:05
You specs are much better than my VM, so you are alright with that :p

**Comment by RomainClaret** [comment] 2016-09-01 21:17
The "dual boot" looks like this when you turn on the computer
<img width="655" alt="screen shot 2016-09-01 at 23 16 27" src="https://cloud.githubusercontent.com/assets/8895475/18184617/22786274-709a-11e6-8fa2-c307d4cd41ce.png">

**Comment by RomainClaret** [comment] 2016-09-01 21:26
Oh, don't forget to customize the variables in script-all_commun-variables.sh
Everything is there, username, password, distribution name, etc...

**Comment by zoecarver** [comment] 2016-09-03 03:00
Awesome! so glad you got it to work, I am currently going through all the steps. Just out of curiosity, Why is it important to do the sequential process? 

thanks again!

**Comment by RomainClaret** [comment] 2016-09-03 08:24
Well, the idea is, if it worked for me, it means that the script (and the modifications) should work on Ubuntu 16.04.01 x64.
The sequential mode is already an automated process, but the auto-pilots are automated automate scripts... Which sometimes makes difficult to see everything that is going on, and where the problems are.
On my side, I would always recommend going sequentially if the semi-auto failed because maybe there is something special about your system that should be taken care of during the process. And also, you could snapshot way more often, like before and after the compilation&checking of GCC (4h).

If you have problems, paste them here :)

**Comment by zoecarver** [comment] 2016-09-04 02:15
I keep getting the error `chroot: failed to run command ‘/tools/bin/env’: No such file or directory
`

**Comment by zoecarver** [comment] 2016-09-04 06:19
Never mind, I think I messed up chapter 5 so I just started over. Thanks!

**Comment by RomainClaret** [comment] 2016-09-04 09:01
Okay :) Give me the chapter and section where the error comes first if you have this problem again :)

**Comment by zoecarver** [comment] 2016-09-04 19:47
on chapter 5.26 it says `... Setup building environment
... Checking uniqueness of tarball
!! Fatal Error 6: 'm4' tarballs is not found.
`
I installed all the tarballs in chapter three i think...

**Comment by RomainClaret** [comment] 2016-09-04 19:54
okay, strange, just wondering, when you run, 0.0-root_initial.sh, you have all the libraries installed? I think m4 is linked to gawk (but I don't remember exactly).
The error is saying that you are missing the "tar" file for this library, which should have been download during "3.all-root_packages-patches.sh", did you notice any errors at this point?

**Comment by zoecarver** [comment] 2016-09-04 20:25
I just re-ran the check for chapter 3. and I got this:

`zoe@zoe-laptop:/mnt/lfs/sources$ md5sum -c md5sums
acl-2.2.52.src.tar.gz: OK
attr-2.4.47.src.tar.gz: OK
autoconf-2.69.tar.xz: OK
automake-1.15.tar.xz: OK
bash-4.3.30.tar.gz: OK
bc-1.06.95.tar.bz2: OK
binutils-2.25.1.tar.bz2: OK
bison-3.0.4.tar.xz: OK
bzip2-1.0.6.tar.gz: OK
check-0.10.0.tar.gz: OK
coreutils-8.24.tar.xz: OK
dejagnu-1.5.3.tar.gz: OK
diffutils-3.3.tar.xz: OK
eudev-3.1.2.tar.gz: OK
e2fsprogs-1.42.13.tar.gz: OK
expat-2.1.0.tar.gz: OK
expect5.45.tar.gz: OK
file-5.24.tar.gz: OK
findutils-4.4.2.tar.gz: OK
flex-2.5.39.tar.xz: OK
gawk-4.1.3.tar.xz: OK
gcc-5.2.0.tar.bz2: OK
gdbm-1.11.tar.gz: OK
gettext-0.19.5.1.tar.xz: OK
glibc-2.22.tar.xz: OK
gmp-6.0.0a.tar.xz: OK
gperf-3.0.4.tar.gz: OK
grep-2.21.tar.xz: OK
groff-1.22.3.tar.gz: OK
grub-2.02~beta2.tar.xz: OK
gzip-1.6.tar.xz: OK
iana-etc-2.30.tar.bz2: OK
inetutils-1.9.4.tar.xz: OK
intltool-0.51.0.tar.gz: OK
iproute2-4.2.0.tar.xz: OK
kbd-2.0.3.tar.xz: OK
kmod-21.tar.xz: OK
less-458.tar.gz: OK
lfs-bootscripts-20150222.tar.bz2: OK
libcap-2.24.tar.xz: OK
libpipeline-1.4.1.tar.gz: OK
libtool-2.4.6.tar.xz: OK
linux-4.2.tar.xz: FAILED
md5sum: m4-1.4.17.tar.xz: No such file or directory
m4-1.4.17.tar.xz: FAILED open or read
md5sum: make-4.1.tar.bz2: No such file or directory
make-4.1.tar.bz2: FAILED open or read
man-db-2.7.2.tar.xz: OK
man-pages-4.02.tar.xz: OK
mpc-1.0.3.tar.gz: OK
mpfr-3.1.3.tar.xz: OK
ncurses-6.0.tar.gz: OK
patch-2.7.5.tar.xz: OK
perl-5.22.0.tar.bz2: OK
pkg-config-0.28.tar.gz: OK
md5sum: procps-ng-3.3.11.tar.xz: No such file or directory
procps-ng-3.3.11.tar.xz: FAILED open or read
md5sum: psmisc-22.21.tar.gz: No such file or directory
psmisc-22.21.tar.gz: FAILED open or read
readline-6.3.tar.gz: OK
sed-4.2.2.tar.bz2: OK
md5sum: shadow-4.2.1.tar.xz: No such file or directory
shadow-4.2.1.tar.xz: FAILED open or read
sysklogd-1.5.1.tar.gz: OK
sysvinit-2.88dsf.tar.bz2: OK
tar-1.28.tar.xz: OK
tcl-core8.6.4-src.tar.gz: OK
texinfo-6.0.tar.xz: OK
md5sum: tzdata2015f.tar.gz: No such file or directory
tzdata2015f.tar.gz: FAILED open or read
udev-lfs-20140408.tar.bz2: OK
util-linux-2.27.tar.xz: OK
vim-7.4.tar.bz2: OK
XML-Parser-2.44.tar.gz: OK
xz-5.2.1.tar.xz: OK
zlib-1.2.8.tar.xz: OK
bash-4.3.30-upstream_fixes-2.patch: OK
bc-1.06.95-memory_leak-1.patch: OK
bzip2-1.0.6-install_docs-1.patch: OK
coreutils-8.24-i18n-1.patch: OK
glibc-2.22-fhs-1.patch: OK
glibc-2.22-upstream_i386_fix-1.patch: OK
kbd-2.0.3-backspace-1.patch: OK
mpfr-3.1.3-upstream_fixes-1.patch: OK
readline-6.3-upstream_fixes-3.patch: OK
sysvinit-2.88dsf-consolidated-1.patch: OK
md5sum: WARNING: 6 listed files could not be read
md5sum: WARNING: 1 computed checksum did NOT match
zoe@zoe-laptop:/mnt/lfs/sources$ popd
`

given that there are some packages missing, do you know how I would install just those? I would rather not reinstall everything because my wifi is REALLY slow and that would take hours.

**Comment by RomainClaret** [comment] 2016-09-04 20:44
stop! you should not install them! You should only download them, that's the source code that your lfs will need!! I recommend you to use my script, which will download them, just modify the destination folder if you want.

**Comment by RomainClaret** [comment] 2016-09-04 20:45
well, you will have to download the source code anyway, no way around :(

**Comment by zoecarver** [comment] 2016-09-04 20:46
I am confused, I downloaded all the tarballs in chapter 3. than i ran chapter 4 and five, and got stuck. then I checked chapter three to make sure all the tarballs where there. am I doing something wrong?

**Comment by RomainClaret** [comment] 2016-09-04 20:47
or! you could download manually the file you need at http://www.linuxfromscratch.org/lfs/view/7.8/wget-list

**Comment by zoecarver** [comment] 2016-09-04 20:47
I feel so stupid right now. I should have just done that...

**Comment by RomainClaret** [comment] 2016-09-04 20:49
Well, what I am reading in your logs, is that during the chapter 3 steps, something went wrong and you don't have the source code for: m4, make, procps, psmisc, shadow, tzdata2015f.tar.gz

**Comment by RomainClaret** [comment] 2016-09-04 20:49
don't worry it happens to everybody :p

**Comment by zoecarver** [comment] 2016-09-04 21:07
after completely restarting the project it still says `chroot: failed to run command ‘/tools/bin/env’: No such file or directory` when I run chapter 6.4

**Comment by RomainClaret** [comment] 2016-09-04 21:19
huh, have you the "I have no name!" ?

**Comment by zoecarver** [comment] 2016-09-04 21:23
no, 

`zoe@zoe-laptop:~/lfs-7.8$ sudo ./6.4-root_chroot-environment.sh 

### ---------------------------

### CHROOT ENVIRONMENT

### CHAPTER 6.4

### Entering the Chroot Environment

### Must be run as "root" user

### ---------------------------

... Loading commun functions and variables

... Validating the environment

/dev/sda4: UUID="6a30f0e1-c2bb-4e41-be73-ad6230bf2fd5" TYPE="ext4" PARTUUID="90b56101-a20c-45f4-ad41-7d3e955cef31"
!! Info: /dev/sda4 is correctly mounted

/dev/sda5                               partition   3639292 0   -2
!! Info: /dev/sda5 is correctly configured as swap

... Entering the Chroot Environment

######### END OF CHAPTER 6.4 ########
///// HUMAN REQUIRED \\\\\
--> Note that the bash prompt will say "I have no name!" This is normal because the /etc/passwd file has not been created yet.

### Please run the next steps:

### cd /tools/lfs

### ./6.all-part-2-chroot_installing-basic-system.sh

chroot: failed to run command ‘/tools/bin/env’: No such file or directory

---> You have exited the shell 3/3

### Please continue the instructions from 6.72

zoe@zoe-laptop:~/lfs-7.8$ 
`

**Comment by zoecarver** [comment] 2016-09-04 21:23
sorry meant for that to be as a code block...

**Comment by RomainClaret** [comment] 2016-09-04 21:32
Okay, so yeah, it's not from scratch :( I would guess that maybe you didn't wipe the LFS partition :/ but I don't know if it's relevant, what I see is that you are not connected to the chroot that's why "/tools/bin/env" doesn't work. `Entering the Chroot Environment` has failed

I am sorry :( But as it is right now, I am a bit stuck also at this point too :/ I would start from scratch again or go back to a snapshot... But you are lucky somehow, the longest part of LFS is the chapter 6.

Oh! Ignore below, it should appear once you exit the chroot : 

```
---> You have exited the shell 3/3

Please continue the instructions from 6.72
```

**Comment by RomainClaret** [comment] 2016-09-04 21:37
I am sorry, but I won't be able to continue support right now, I am going to sleep now :( Good night :)

**Comment by zoecarver** [comment] 2016-09-05 00:01
OK,  thanks again!

**Comment by zoecarver** [comment] 2016-09-05 22:09
Do you have any good resources I could use so I don't by have to bother you every time I have an issue?

**Comment by RomainClaret** [comment] 2016-09-05 22:10
What do you mean? Like the LFS book?

**Comment by zoecarver** [comment] 2016-09-06 02:49
so I have completely erased and restarted the project again, and I am still getting the same error... any ideas? 

error:
`chroot: failed to run command ‘/tools/bin/env’: No such file or directory when I run chapter 6.4`

**Comment by RomainClaret** [comment] 2016-09-06 06:40
I am really sorry :( 
I found this that could related http://www.linuxquestions.org/questions/linux-from-scratch-13/chroot-cannot-run-command-%60-tools-bin-env'-no-such-file-or-directory-360369/

**Comment by zoecarver** [comment] 2016-09-11 00:26
I found the answer to the `chroot: failed to run command ‘/tools/bin/env’: No such file or directory when I run chapter 6.4` problem, I needed to be on ubuntu 14. however now I have a new problem, the lfs system should be part of grub, but it is not...

<img width="1281" alt="screen shot 2016-09-10 at 5 24 10 pm" src="https://cloud.githubusercontent.com/assets/13806068/18414411/aa15f786-777b-11e6-9724-f74787a835d5.png">
<img width="640" alt="screen shot 2016-09-10 at 5 26 43 pm" src="https://cloud.githubusercontent.com/assets/13806068/18414414/c50f47a4-777b-11e6-97d7-47dc3dc883ec.png">

**Comment by zoecarver** [comment] 2016-09-11 00:27
also this time i did it in a virtual box...

**Comment by zoecarver** [comment] 2016-09-11 01:01
here is a snapshot: 
https://drive.google.com/open?id=0B1KZa-7dVNsnVkRJYlB1ckYxRUE

thanks! ;)

**Comment by RomainClaret** [comment] 2016-09-11 08:44
Okay 👌🏻 I will try to check it out tomorrow (busy irl today)
Meanwhile did you use the manual commands from 9.1? logout and update-grub
Also, in case you did some customization, did you update the variables in script-all_commun-variables?

**Comment by zoecarver** [comment] 2016-09-13 02:42
I did update the variables, but I just changed some of the strings, nothing major... I am following this, not sure if it will help. is there anything special I need to do ? thanks! 

[link:] http://www.linuxquestions.org/questions/linux-from-scratch-13/booting-lfs-7-0-with-grub2-921286/#post4562463

**Comment by RomainClaret** [comment] 2016-09-13 17:36
Hello, I could download and run your image, is it possible to have the root password?

**Comment by zoecarver** [comment] 2016-09-13 23:48
ok I now got it... but I am now getting this error :( thanks for you help! 
<img width="720" alt="screen shot 2016-09-13 at 4 47 36 pm" src="https://cloud.githubusercontent.com/assets/13806068/18495317/e0f1c372-79d1-11e6-9c6c-bbc656bd1800.png">

**Comment by zoecarver** [comment] 2016-09-17 03:13
YAY I got it to work!!! I just needed to use virtual box instead of vmware. I cant believe it! I made my first LFS system! Thank you so much for all of your help! 👍 :)

**Comment by RomainClaret** [comment] 2016-09-18 16:14
Great news!! I am really happy for you!
But I am still wondering what is wrong with VMWare and the bootable USB key....
I will do tests when I have some free time again u_u

**Closed as completed** 2016-12-08 13:41 UTC
